  backend:
    name: github
    repo: [username]/cornell-ipm-guidelines-demo
    branch: main

  media_folder: "static/images"
  public_folder: "/images"

  collections:
    - name: "guideline"
      label: "Sample Guideline"
      folder: "content/sample-guideline"
      create: false
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}