backend:
  name: github
  repo: nysipm/cornell-ipm-guidelines-demo  # Replace with your username/repo
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "guideline"
    label: "Guidelines"
    folder: "content/sample-guideline"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}